# Generated by Django 6.0.6 on 2026-08-14 12:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=500, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за час')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('is_high_edu', models.BooleanField(default=False, verbose_name='Есть высшее образование')),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Возраст')),
                ('experience_years', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Лет опыта')),
                ('bio', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('favorites_by', models.ManyToManyField(blank=True, related_name='favorite_tutors', to=settings.AUTH_USER_MODEL, verbose_name='В избранном у')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Репетитор',
                'verbose_name_plural': 'Репетиторы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='Имя студента')),
                ('student_email', models.EmailField(max_length=254, verbose_name='Email студента')),
                ('student_phone', models.CharField(max_length=20, verbose_name='Телефон студента')),
                ('scheduled_at', models.DateTimeField(verbose_name='Дата и время урока')),
                ('duration_minutes', models.IntegerField(choices=[(30, '30 мин'), (60, '60 мин'), (90, '90 мин'), (120, '120 мин')], verbose_name='Длительность (мин)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Итоговая стоимость')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.discipline', verbose_name='Предмет')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='app.tutor', verbose_name='Репетитор')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.AddField(
            model_name='discipline',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='app.tutor', verbose_name='Преподаватель'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Студент'), ('tutor', 'Репетитор')], max_length=10, verbose_name='Роль')),
                ('avatar', models.ImageField(blank=True, upload_to='photos', verbose_name='Аватар')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.tutor', verbose_name='Репетитор')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'unique_together': {('tutor', 'student')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='discipline',
            unique_together={('tutor', 'slug')},
        ),
    ]
