# Generated by Django 6.1 on 2026-08-12 08:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('durations', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('phone_number', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, upload_to='photos')),
                ('is_blocked', models.BooleanField(db_default=False)),
                ('is_high_edu', models.BooleanField(db_default=False)),
                ('age', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Репетитор',
                'verbose_name_plural': 'Репетиторы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('phone_number', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, upload_to='photos')),
                ('is_blocked', models.BooleanField(db_default=False)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, max_length=250)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.discipline')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tutor')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='discipline',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tutor'),
        ),
    ]
