# Generated by Django 6.1 on 2026-08-24 12:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='bio',
            new_name='about',
        ),
        migrations.AddField(
            model_name='tutor',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discipline',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за час'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='experience_years',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Лет опыта'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='is_high_edu',
            field=models.BooleanField(default=False, verbose_name='Высшее образование'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Профиль', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Messagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.CharField(unique=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagers', to='app.tutor', verbose_name='Месседжеры')),
            ],
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
