# Generated by Django 6.0.6 on 2026-08-13 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tutor_created_at_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='favorites_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_tutors', to='app.user', verbose_name='В избранном у'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='durations',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='длительность'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=20, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='avatar',
            field=models.ImageField(blank=True, default='photos/OIP-2342034818.jpg', upload_to='photos'),
        ),
    ]
